development:
  sessions:
    default:
      uri: mongodb://127.0.0.1:27017/timetrack_dev
      options:
        consistency: strong

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true

